#!/bin/bash

echo "🔄 Restarting Poker Chips Servers..."
echo ""
echo "⚠️  Go to your terminal windows and:"
echo ""
echo "1️⃣  BACKEND (server terminal):"
echo "   Press Ctrl+C to stop"
echo "   Then run: npm start"
echo ""
echo "2️⃣  FRONTEND (main terminal):"
echo "   It should auto-reload, but if not:"
echo "   Press Ctrl+C to stop"
echo "   Then run: npm start"
echo ""
echo "3️⃣  After restarting:"
echo "   - Refresh your browser (Cmd+R or Ctrl+R)"
echo "   - Start a NEW game (old game won't have the fixes)"
echo "   - Try betting again!"
echo ""
echo "✅ You should see in server terminal:"
echo "   'Received add-to-pot request: code=XXX, amount=25'"
echo "   '✅ Added 25 to pot (now 25) in game: XXX'"
echo ""

